#!/bin/bash
#SBATCH --job-name=scDNA_sim_hiscanner
#SBATCH --mem=32G
#SBATCH --cpus-per-task=16
#SBATCH --time=48:00:00
#SBATCH --output=logs/hiscanner_scDNA_sim_%j.out
#SBATCH --error=logs/hiscanner_scDNA_sim_%j.err

# All settings live in config.sh (HiScanner section).
# This script writes HiScanner's metadata.txt, config.yaml and cluster.yaml
# from those settings, checks inputs, then runs the requested steps.

source "./config.sh"

source ${CONDA}
conda activate ${HS_ENV}

set -euo pipefail

SCAN2_OUT="${PROJECT_DIR}/scan2_out"
BAM_DIR="${PROJECT_DIR}/sim/bams"
BULK_BAM="${PROJECT_DIR}/sim/bulk/bams/bulk.bam"
BULK_SAMPLE="bulk"

mkdir -p "${HS_DIR}"

die() { echo "ERROR: $*" >&2; exit 1; }

# ============================================================
# Checks
# ============================================================

for tool in hiscanner bcftools samtools snakemake Rscript; do
    command -v "$tool" >/dev/null || die "'$tool' not found in env ${HS_ENV}"
done

for f in \
    "${SCAN2_OUT}/gatk/hc_raw.mmq60.vcf.gz" \
    "${SCAN2_OUT}/gatk/hc_raw.mmq60.vcf.gz.tbi" \
    "${SCAN2_OUT}/shapeit/phased_hets.vcf.gz" \
    "${SCAN2_OUT}/shapeit/phased_hets.vcf.gz.tbi" \
    "${BULK_BAM}"; do
    [[ -f $f ]] || die "missing $f"
done

for c in ${HS_CHROMS}; do
    # HiScanner's Snakefile hard-codes the .fasta extension
    [[ -f "${FASTA_SPLIT_DIR}/${c}.fasta" ]] || die "missing ${FASTA_SPLIT_DIR}/${c}.fasta"
    [[ -f "${MAPPABILITY_STEM}${c}.txt" ]]   || die "missing mappability file ${MAPPABILITY_STEM}${c}.txt (check MAPPABILITY_STEM)"
done

LAST_SAMPLE=$(bcftools query -l "${SCAN2_OUT}/shapeit/phased_hets.vcf.gz" | tail -n 1)
[[ ${LAST_SAMPLE} == phasedgt ]] \
    || die "phased_hets.vcf.gz sample column is '${LAST_SAMPLE}', not phasedgt"

    
if [[ ${HS_USE_CLUSTER} == true && -z ${SLURM_ACCOUNT} ]]; then
    die "HS_USE_CLUSTER=true but SLURM_ACCOUNT is empty (HiScanner always passes --account to sbatch)"
fi

# ============================================================
# metadata.txt  (bamID must equal the sample name in the SCAN2 VCF)
# ============================================================

META="${HS_DIR}/metadata.txt"
{
    printf 'bamID\tbam\tsinglecell\n'
    printf '%s\t%s\tN\n' "${BULK_SAMPLE}" "${BULK_BAM}"
    for b in "${BAM_DIR}"/*.bam; do
        printf '%s\t%s\tY\n' "$(basename "$b" .bam)" "$b"
    done
} > "${META}"

N_CELLS=$(( $(wc -l < "${META}") - 2 ))
echo "Wrote ${META}: ${N_CELLS} cells + bulk"

# Every bamID must be a sample in hc_raw.mmq60.vcf.gz, or HiScanner's bcftools -s fails
MISSING=$(comm -23 \
    <(tail -n +2 "${META}" | cut -f1 | LC_ALL=C sort) \
    <(bcftools query -l "${SCAN2_OUT}/gatk/hc_raw.mmq60.vcf.gz" | LC_ALL=C sort))
[[ -z ${MISSING} ]] || die "bamIDs not found in SCAN2 VCF (read-group SM mismatch?):
${MISSING}"

# ============================================================
# config.yaml
# ============================================================

CHROM_YAML=$(printf '"%s", ' ${HS_CHROMS})
CHROM_YAML="[${CHROM_YAML%, }]"

cat > "${HS_DIR}/config.yaml" <<EOF
# Generated by hiscanner_run.sh from config.sh -- edit config.sh, not this file
scan2_output: ${SCAN2_OUT}
metadata_path: ${META}
outdir: ${HS_DIR}/output
use_multisample_segmentation: ${HS_MULTISAMPLE}

fasta_folder: ${FASTA_SPLIT_DIR}
mappability_folder_stem: ${MAPPABILITY_STEM}

rdr_only: ${HS_RDR_ONLY}
binsize: ${HS_BINSIZE}
chrom_list: ${CHROM_YAML}
lambda_range: ${HS_LAMBDA_RANGE}
lambda_value: ${HS_LAMBDA}
max_wgd: ${HS_MAX_WGD}
batch_size: ${HS_BATCH_SIZE}
depth_filter: ${HS_DEPTH_FILTER}
ado_threshold: ${HS_ADO_THRESHOLD}
threads: ${HS_THREADS}
ado_plot_baf_distribution: ${HS_ADO_PLOTS}

aggregate_every_k_snp: ${HS_AGGREGATE_K}
k: ${HS_K}

keep_raw_files: false
rerun: ${HS_RERUN}
keep_temp_files: false

use_cluster: ${HS_USE_CLUSTER}
cluster_queue: "${SLURM_PARTITION}"
max_cluster_jobs: 100
EOF

# ============================================================
# cluster.yaml  (only used by: hiscanner run --step normalize --use-cluster)
# ============================================================

cat > "${HS_DIR}/cluster.yaml" <<EOF
__default__:
  account: "${SLURM_ACCOUNT}"
  partition: "${SLURM_PARTITION}"
  time: "12:00:00"
  nodes: 1
  ntasks: 1
  mem: "4G"
  job-name: "hiscanner_{rule}"
  output: "cluster_logs/{rule}-%j.out"
  error: "cluster_logs/{rule}-%j.err"

get_read_pos:
  time: "4:00:00"
  mem: "4G"
  ntasks: 1
  partition: "${SLURM_PARTITION}"

run_bicseq_norm:
  time: "12:00:00"
  mem: "16G"
  ntasks: 4
  partition: "${SLURM_PARTITION}"
EOF

# ============================================================
# Run
# ============================================================

# HiScanner looks for config.yaml / cluster.yaml in the working directory
cd "${HS_DIR}"

hiscanner validate config.yaml

FLAGS=()
[[ ${HS_RERUN} == true ]] && FLAGS+=(--rerun)

for step in ${HS_STEPS}; do
    if [[ ${HS_RDR_ONLY} == true && ${step} =~ ^(snp|phase|ado)$ ]]; then
        echo "Skipping ${step} (RDR-only mode)"
        continue
    fi

    STEP_FLAGS=("${FLAGS[@]+"${FLAGS[@]}"}")
    [[ ${step} == normalize && ${HS_USE_CLUSTER} == true ]] && STEP_FLAGS+=(--use-cluster)

    echo "=== hiscanner: ${step} ==="
    hiscanner --config config.yaml run --step "${step}" "${STEP_FLAGS[@]+"${STEP_FLAGS[@]}"}"
done

echo "HiScanner finished. Results: ${HS_DIR}/output/final_calls"