#!/bin/bash
#SBATCH --job-name=phase_ugp
#SBATCH --mem=64G
#SBATCH --cpus-per-task=16
#SBATCH --time=48:00:00
#SBATCH --output=logs/phase_ugp_%j.out
#SBATCH --error=logs/phase_ugp_%j.err

# Universal Genotyping Pipeline (raphael-group) on the simulated data.
# All settings live in config.sh (UGP section). This script writes the
# sample sheet (samples.json) and config.yaml, then runs Snakemake.
#
#   UGP_MODE=bulk    -> genotype + phase the bulk only; stops at phase/phased_het_snps.vcf.gz
#   UGP_MODE=percell -> also add every cell as its own scDNA "tumor" dataset and run
#                       through combine_counts (bins x cells RDR + phased allele counts)
#
# Submitted by run_pipeline.sh --phaser ugp. Output for callers:
#   ${UGP_DIR}/out/phase/phased_het_snps.vcf.gz
# Snakemake dry run on the login node (from sim/):
#   UGP_DRYRUN=true bash scripts/phase_ugp.sh

LOG_TAG=phase_ugp
source "${CONFIG_FILE:-./config.sh}"
source ./scripts/common.sh

source ${CONDA}
conda activate ${UGP_ENV}

set -euo pipefail

UGP_DRYRUN=${UGP_DRYRUN:-false}

BAM_DIR="${CELL_BAM_DIR}"
BULK_ID="bulk"
DATA="${UGP_REPO}/resources/data"


# ============================================================
# Checks
# ============================================================

command -v snakemake >/dev/null || die "snakemake not found in ${UGP_ENV}"
SMK_MAJOR=$(snakemake --version | cut -d. -f1)
(( SMK_MAJOR >= 9 )) || die "UGP needs Snakemake >= 9 (found $(snakemake --version)); use its own env"

[[ ${UGP_MODE} == bulk || ${UGP_MODE} == percell ]] || die "UGP_MODE must be 'bulk' or 'percell'"

for f in "${UGP_REPO}/workflow/Snakefile" "${REF}" "${REF}.fai" "${BULK_BAM}" "${BULK_BAM}.bai" \
         "${UGP_GTF}" "${UGP_SNP_PANEL}" "${EAGLE_GENMAP}" \
         "${DATA}/hg38.chrom.sizes" "${DATA}/hg38.regions.bed" "${DATA}/windows.1kbp.hg38.bed.gz"; do
    [[ -e $f ]] || die "missing $f"
done
[[ -e ${UGP_SNP_PANEL}.tbi || -e ${UGP_SNP_PANEL}.csi ]] || die "snp_panel not indexed: tabix -p vcf ${UGP_SNP_PANEL}"

for c in ${UGP_CHROMS}; do
    [[ -e "${UGP_PHASING_PANEL}/chr${c}.genotypes.bcf" ]] \
        || die "missing ${UGP_PHASING_PANEL}/chr${c}.genotypes.bcf (UGP's required name)"
done

mkdir -p "${UGP_DIR}"

# ============================================================
# Cells (percell mode)
# ============================================================

CELL_BAMS=()
if [[ ${UGP_MODE} == percell ]]; then
    mapfile -t CELL_BAMS < <(ls "${BAM_DIR}"/*.bam | LC_ALL=C sort)
    (( ${#CELL_BAMS[@]} > 0 )) || die "no cell BAMs in ${BAM_DIR}"
    if (( UGP_MAX_CELLS > 0 && ${#CELL_BAMS[@]} > UGP_MAX_CELLS )); then
        CELL_BAMS=("${CELL_BAMS[@]:0:${UGP_MAX_CELLS}}")
    fi
    echo "percell mode: ${#CELL_BAMS[@]} cells"
fi

# ============================================================
# samples.json
# ============================================================

SAMPLES_JSON="${UGP_DIR}/samples.json"
CELL_LIST="${UGP_DIR}/cell_bams.txt"
printf '%s\n' "${CELL_BAMS[@]+"${CELL_BAMS[@]}"}" > "${CELL_LIST}"

python3 - "${SAMPLES_JSON}" "${UGP_SAMPLE_ID}" "${BULK_ID}" "${BULK_BAM}" "${CELL_LIST}" <<'PY'
import json, os, sys
out, sample_id, bulk_id, bulk_bam, cell_list = sys.argv[1:6]

def rec(dataset_id, assay, stype, bam, base=None):
    r = {
        "sample_id": sample_id,
        "dataset_id": dataset_id,
        "assay_type": assay,
        "sample_type": stype,
        "reference_version": "hg38",
        "files": {"alignment": bam, "alignment_index": bam + ".bai"},
    }
    if base:
        r["rdr_base_dataset_id"] = base
    return r

samples = [rec(bulk_id, "bulkWGS", "normal", bulk_bam)]
for line in open(cell_list):
    bam = line.strip()
    if not bam:
        continue
    cell = os.path.basename(bam)[:-len(".bam")]
    samples.append(rec(cell, "scDNA", "tumor", bam, base=bulk_id))

with open(out, "w") as f:
    json.dump({"version": 1, "samples": samples}, f, indent=2)
print(f"Wrote {out}: {len(samples)} datasets")
PY

# ============================================================
# config.yaml
# ============================================================

CHROM_YAML="[$(echo ${UGP_CHROMS} | sed 's/ /, /g')]"
if [[ ${UGP_MODE} == percell ]]; then
    ASSAYS='["bulkWGS", "scDNA"]'
else
    ASSAYS='["bulkWGS"]'
fi

cat > "${UGP_DIR}/config.yaml" <<EOF
# Generated by scripts/phase_ugp.sh from config.sh -- edit config.sh, not this file
workflow_mode: "bulk_genotyping"
assay_types: ${ASSAYS}

sample_id: ${UGP_SAMPLE_ID}
dataset_ids: []
sample_file: ${SAMPLES_JSON}
chromosomes: ${CHROM_YAML}

het_snp_vcf: null
het_snp_vcf_phased: true
bb_file: null

species: human
reference_version: "hg38"
reference: ${REF}
gtf_file: ${UGP_GTF}
genome_size: ${DATA}/hg38.chrom.sizes
region_bed: ${DATA}/hg38.regions.bed
extremity_tsv: null

blacklist_bed: ${DATA}/hg38-blacklist.v2.bed.gz
gene_blacklist_file: ${DATA}/ig_gene_list.txt

# Pre-built 1 kb grid already carries GC, MAP and REPLI columns
window_bed: ${DATA}/windows.1kbp.hg38.bed.gz
mappability_bed: null
target_bed: null

snp_panel: ${UGP_SNP_PANEL}
genotype_dataset_ids: ["${BULK_ID}"]
panel_allele_only: true

phaser: "eagle"
phasing_panel: ${UGP_PHASING_PANEL}
gmap_path: ${EAGLE_GENMAP}

params_combine_counts:
  detect_loh_tumor_cell_line: false
  min_snp_reads: ${UGP_MIN_SNP_READS}
  min_snp_per_bin: ${UGP_MIN_SNP_PER_BIN}
  min_total_reads: ${UGP_MIN_TOTAL_READS}
  gene_aware_binning: ${UGP_GENE_AWARE_BINNING}

threads:
  genotype: ${UGP_THREADS_GENOTYPE}
  phase: ${UGP_THREADS_PHASE}
  pileup: ${UGP_THREADS_PILEUP}
  mosdepth: ${UGP_THREADS_MOSDEPTH}
EOF

# ============================================================
# Run
# ============================================================

TARGETS=()
[[ ${UGP_MODE} == bulk ]] && TARGETS=(phase/phased_het_snps.vcf.gz)

SMK_ARGS=(
    --profile "${UGP_REPO}/profile/"
    -s "${UGP_REPO}/workflow/Snakefile"
    --configfile "${UGP_DIR}/config.yaml"
    --directory "${UGP_DIR}/out"
    --config sample_file="${SAMPLES_JSON}" sample_id="${UGP_SAMPLE_ID}"
    --conda-prefix "${UGP_CONDA_PREFIX}"
    --rerun-incomplete
)

if [[ ${UGP_EXECUTOR:-local} == slurm ]]; then
    SMK_ARGS+=(--executor slurm --jobs 100
               --default-resources slurm_partition="${SLURM_PARTITION}" slurm_account="${SLURM_ACCOUNT}" mem_mb=8000 runtime=240)
else
    SMK_ARGS+=(--cores "${UGP_CORES}")
fi

mkdir -p "${UGP_DIR}/out"

if [[ ${UGP_DRYRUN} == true ]]; then
    snakemake "${SMK_ARGS[@]}" --dry-run "${TARGETS[@]+"${TARGETS[@]}"}"
else
    snakemake "${SMK_ARGS[@]}" "${TARGETS[@]+"${TARGETS[@]}"}"
    echo "UGP finished: ${UGP_DIR}/out"
fi